/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2025-12-18 14:18:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class book_005fmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Minecraft/插件制作/插件开发空间/Library-Manage-System/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1766056243713L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"图书 java jsp\"/>\r\n");
      out.write("    <meta http-equiv=\"author\" content=\"phenix\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./Style/skin.css\"/>\r\n");
      out.write("    <script src=\"Js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        //图片预览\r\n");
      out.write("        function getFullPath(obj) {\r\n");
      out.write("            if (obj) {\r\n");
      out.write("                //ie\r\n");
      out.write("                if (window.navigator.userAgent.indexOf(\"MSIE\") >= 1) {\r\n");
      out.write("                    obj.select();\r\n");
      out.write("                    return document.selection.createRange().text;\r\n");
      out.write("                } else if (window.navigator.userAgent.indexOf(\"Firefox\") >= 1) {\r\n");
      out.write("                    //firefox　\r\n");
      out.write("                    return window.URL.createObjectURL(obj.files.item(0));\r\n");
      out.write("                } else if (navigator.userAgent.indexOf(\"Chrome\") > 0) {\r\n");
      out.write("                    //chrome\r\n");
      out.write("                    return window.URL.createObjectURL(obj.files.item(0));\r\n");
      out.write("                }\r\n");
      out.write("                return obj.value;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#filePic\").change(function () {\r\n");
      out.write("                var path = getFullPath($(this)[0]);\r\n");
      out.write("                console.log(path);\r\n");
      out.write("                $(\"#imgPic\").prop(\"src\", path);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <!-- 头部开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"17\" valign=\"top\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/left_top_right.gif\" width=\"17\" height=\"29\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"top\" background=\"./Images/content_bg.gif\">\r\n");
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"16\" valign=\"top\" background=\"./Images/mail_right_bg.gif\"><img src=\"./Images/nav_right_bg.gif\"\r\n");
      out.write("                                                                                 width=\"16\" height=\"29\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 中间部分开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <!--第一行左边框-->\r\n");
      out.write("        <td valign=\"middle\" background=\"./Images/mail_left_bg.gif\">&nbsp;</td>\r\n");
      out.write("        <!--第一行中间内容-->\r\n");
      out.write("        <td valign=\"top\" bgcolor=\"#F7F8F9\">\r\n");
      out.write("            <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <!-- 空白行-->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td valign=\"top\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"4\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"100\" align=\"center\"><img src=\"./Images/mime.gif\"/></td>\r\n");
      out.write("                                <td valign=\"bottom\"><h3 style=\"letter-spacing:1px;\">书籍管理 > 修改书籍</h3></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 一条线 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 添加产品开始 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp</td>\r\n");
      out.write("                    <td width=\"96%\">\r\n");
      out.write("                        <table width=\"100%\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\">\r\n");
      out.write("                                    <form action=\"book?type=modify\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                        <table width=\"100%\" class=\"cont\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>编号：</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" type=\"text\" name=\"id\"\r\n");
      out.write("                                                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/></td>\r\n");
      out.write("                                                <td rowspan=\"8\" valign=\"top\">\r\n");
      out.write("                                                    <fieldset style=\"width: 210px; height: 370px;\">\r\n");
      out.write("                                                        <legend>图片预览</legend>\r\n");
      out.write("                                                        <img id=\"imgPic\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"200px\"\r\n");
      out.write("                                                             height=\"350px\"/>\r\n");
      out.write("                                                    </fieldset>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td width=\"15%\">名称：</td>\r\n");
      out.write("                                                <td width=\"25%\"><input class=\"text\" type=\"text\" name=\"name\"\r\n");
      out.write("                                                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>类型：</td>\r\n");
      out.write("                                                <td width=\"20%\">\r\n");
      out.write("                                                    <select id=\"book_type\" name=\"typeId\">\r\n");
      out.write("                                                        <option value=\"0\">---请选择---</option>\r\n");
      out.write("                                                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                    </select>\r\n");
      out.write("                                                </td>\r\n");
      out.write("\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>图片：</td>\r\n");
      out.write("                                                <!--\r\n");
      out.write("                                                  1.用户不需要修改封面(不会选择图片) filePic.value==>后台 文件名:\"\" 数据库中应该保存之前的图片路径\r\n");
      out.write("                                                  2.用户需要修改封面，文件上传(保存文件)\r\n");
      out.write("                                                -->\r\n");
      out.write("                                                <td width=\"20%\">\r\n");
      out.write("                                                    <!--保存之前的图片路径  book.pic -->\r\n");
      out.write("                                                    <input type=\"hidden\" name=\"pic\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                                    <input type=\"file\" id=\"filePic\" name=\"filePic\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>库存量：</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" style=\"width:50px;\" type=\"number\"\r\n");
      out.write("                                                                       name=\"stock\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>单价：</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" style=\"width:100px;\" type=\"text\"\r\n");
      out.write("                                                                       name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>出版社：</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" type=\"text\" name=\"publish\"\r\n");
      out.write("                                                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.publish}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>作者:</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" type=\"text\" name=\"author\"\r\n");
      out.write("                                                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td>存放地址:</td>\r\n");
      out.write("                                                <td width=\"20%\"><input class=\"text\" type=\"text\" name=\"address\"\r\n");
      out.write("                                                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>&nbsp;</td>\r\n");
      out.write("                                                <td>简介：</td>\r\n");
      out.write("                                                <td colspan=\"2\"><textarea cols=\"150\" rows=\"20\"\r\n");
      out.write("                                                                          name=\"desc\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>&nbsp;</td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td colspan=\"3\"><input class=\"btn\" type=\"submit\" value=\"提交\"/></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 添加产品结束 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"51%\" class=\"left_txt\">\r\n");
      out.write("                        <img src=\"./Images/icon_mail.gif\" width=\"16\" height=\"11\"> 客户服务邮箱：1109132@qq.com<br/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/mail_right_bg.gif\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 底部部分 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_left.gif\" width=\"17\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/buttom_bgs.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_bgs.gif\" width=\"17\" height=\"17\">\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_right_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_right.gif\" width=\"16\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /book_modify.jsp(122,56) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${types}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /book_modify.jsp(122,56) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("t");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                            ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                                            ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                                                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /book_modify.jsp(123,60) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.typeId== t.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                                                <option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" selected>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("                                                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /book_modify.jsp(126,60) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.typeId!=t.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                                                <option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("                                                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
