/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2025-12-18 14:17:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class book_005frent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"图书 java jsp\"/>\r\n");
      out.write("    <meta http-equiv=\"author\" content=\"phenix\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./Style/skin.css\"/>\r\n");
      out.write("    <script src=\"Js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        /**\r\n");
      out.write("         * 获取系统的当前时间\r\n");
      out.write("         *  2021-02-12\r\n");
      out.write("         **/\r\n");
      out.write("        function getCurrentDate() {\r\n");
      out.write("            var dateObj = new Date();\r\n");
      out.write("            var year = dateObj.getFullYear();\r\n");
      out.write("            var month = dateObj.getMonth() + 1;//0~ 11\r\n");
      out.write("            var date = dateObj.getDate();\r\n");
      out.write("            var dateStr = year + \"-\" + (month >= 10 ? month : \"0\" + month) + \"-\" + (date >= 10 ? date : \"0\" + date);\r\n");
      out.write("            return dateStr;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /**\r\n");
      out.write("         * 获取归还时间\r\n");
      out.write("         * count:借阅时间\r\n");
      out.write("         * 2012-12-1 : 20\r\n");
      out.write("         * 2012-12-21:归还\r\n");
      out.write("         * 毫秒: 1s = 1000ms   1m = 60s   1h= 60m   1d = 24h\r\n");
      out.write("         *\r\n");
      out.write("         * */\r\n");
      out.write("        function getBackDate(count) {\r\n");
      out.write("            //1.获取系统的当前时间\r\n");
      out.write("            var dateObj = new Date();\r\n");
      out.write("            //2.转成毫秒数\r\n");
      out.write("            var mills = dateObj.getMilliseconds();\r\n");
      out.write("            //3\r\n");
      out.write("            mills += count * 24 * 60 * 60 * 1000;\r\n");
      out.write("            //4.转成日期出来\r\n");
      out.write("            dateObj.setMilliseconds(mills);\r\n");
      out.write("\r\n");
      out.write("            //5.时间转成字符串\r\n");
      out.write("            var year = dateObj.getFullYear();\r\n");
      out.write("            var month = dateObj.getMonth() + 1;//0~ 11\r\n");
      out.write("            var date = dateObj.getDate();\r\n");
      out.write("            var dateStr = year + \"-\" + (month >= 10 ? month : \"0\" + month) + \"-\" + (date >= 10 ? date : \"0\" + date);\r\n");
      out.write("            return dateStr;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#btnQueryBook\").prop(\"disabled\", \"disabled\");\r\n");
      out.write("            $(\"#btnSubmit\").prop(\"disabled\", \"disabled\");\r\n");
      out.write("            var member = null;\r\n");
      out.write("            $(\"#btnQuery\").click(function () {\n");
      out.write("                //1.获取用户输入的身份证号\n");
      out.write("                var content = $(\"#memberId\").val();\n");
      out.write("                //判断为null ,\"\"\n");
      out.write("                if (!content) {\n");
      out.write("                    alert(\"请输入用户号\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var queryBtn = $(this);\n");
      out.write("                queryBtn.prop(\"disabled\", \"disabled\");\n");
      out.write("                var url = \"member?type=doajax&idn=\" + content;\n");
      out.write("                $.get(url, function (data, status) {\n");
      out.write("                    //json字符串\n");
      out.write("                    console.log(data);\n");
      out.write("\n");
      out.write("                    if (!data || data === \"{}\") {\n");
      out.write("                        alert(\"未找到会员信息\");\n");
      out.write("                        member = null;\n");
      out.write("                        queryBtn.removeAttr(\"disabled\");\n");
      out.write("                        $(\"#btnQueryBook\").prop(\"disabled\", \"disabled\");\n");
      out.write("                        $(\"#name\").val(\"\");\n");
      out.write("                        $(\"#type\").val(\"\");\n");
      out.write("                        $(\"#amount\").val(\"\");\n");
      out.write("                        $(\"#balance\").val(\"\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    //1.json字符串--》json对象\n");
      out.write("                    member = JSON.parse(data);\n");
      out.write("\n");
      out.write("                    // 打印信息到控制台\n");
      out.write("                    console.log(member.balance + \",\" + member.type.name + \",\" + member.type.amount + \",\" + member.name);\n");
      out.write("                    //2.给组件赋值\n");
      out.write("                    $(\"#name\").val(member.name);\n");
      out.write("                    $(\"#type\").val(member.type.name);\n");
      out.write("                    $(\"#amount\").val(member.type.amount);\n");
      out.write("                    $(\"#balance\").val(member.balance);\n");
      out.write("\n");
      out.write("                    $(\"#btnQueryBook\").removeAttr(\"disabled\");\n");
      out.write("                }).fail(function () {\n");
      out.write("                    alert(\"查询会员信息失败，请稍后重试\");\n");
      out.write("                    queryBtn.removeAttr(\"disabled\");\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\"#memberId\").on(\"input\", function () {\n");
      out.write("                member = null;\n");
      out.write("                $(\"#btnQuery\").removeAttr(\"disabled\");\n");
      out.write("                $(\"#btnQueryBook\").prop(\"disabled\", \"disabled\");\n");
      out.write("            });\n");
      out.write("\r\n");
      out.write("            //保存所有添加过的书名\n");
      out.write("            var bookNameList = [];\n");
      out.write("            $(\"#btnQueryBook\").click(function () {\n");
      out.write("                if (!member) {\n");
      out.write("                    alert(\"请先查询会员信息\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var name = $(\"#bookContent\").val();\n");
      out.write("                if (!name) {\n");
      out.write("                    alert(\"请输入书籍名称\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var url = \"book?type=doajax&name=\" + name;\n");
      out.write("                $.get(url, function (data, status) {\n");
      out.write("                    //{}/一本书的json\n");
      out.write("                    console.log(data);\n");
      out.write("                    //特殊情况 {}\n");
      out.write("                    if (data === \"{}\") {\n");
      out.write("                        alert(\"当前书籍不存在，查找失败\");\n");
      out.write("                        $(\"#bookContent\").val(\"\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    //判断这本书名是否存在过\n");
      out.write("                    if (bookNameList.indexOf(name) >= 0) {\n");
      out.write("                        alert(\"当前书籍已添加，添加失败\");\n");
      out.write("                        return;\n");
      out.write("                    }\n");
      out.write("                    //添加书名到数组\n");
      out.write("                    bookNameList.push(name);\n");
      out.write("                    var book = JSON.parse(data);\n");
      out.write("                    /**\n");
      out.write("                     *<tr align=\"center\" class=\"d\">\n");
      out.write("                     <td><input type=\"checkbox\" value=\"1\" checked  class=\"ck\" /></td>\n");
      out.write("                     <td>罗小黑战记</td>\n");
      out.write("                     <td>2010-10-01</td>\n");
      out.write("                     <td>2010-10-31</td>\n");
      out.write("                     <td>北京联合出版社</td>\n");
      out.write("                     <td>东区-01-02</td>\n");
      out.write("                     <td>39.9</td>\n");
      out.write("                     </tr>\n");
      out.write("                     */\n");
      out.write("                    var tr = $(\"<tr align=\\\"center\\\" class=\\\"d\\\">\");\n");
      out.write("                    var tdCheck = $(\"<td><input type=\\\"checkbox\\\" value=\\\"\" + book.id + \"\\\" class=\\\"ck\\\" checked /></td>\");\n");
      out.write("                    var tdName = $(\"<td>\" + book.name + \"</td>\");\n");
      out.write("                    var tdRentDate = $(\"<td>\" + getCurrentDate() + \"</td>\");\n");
      out.write("                    var tdBackDate = $(\"<td>\" + getBackDate(member.type.keepDay) + \"</td>\");\n");
      out.write("                    var tdPublish = $(\"<td>\" + book.publish + \"</td>\");\n");
      out.write("                    var tdAddress = $(\"<td>\" + book.address + \"</td>\");\n");
      out.write("                    var tdPrice = $(\"<td>\" + book.price + \"</td>\");\n");
      out.write("\n");
      out.write("                    tr.append(tdCheck);\n");
      out.write("                    tr.append(tdName);\n");
      out.write("                    tr.append(tdRentDate);\n");
      out.write("                    tr.append(tdBackDate);\n");
      out.write("                    tr.append(tdPublish);\n");
      out.write("                    tr.append(tdAddress);\n");
      out.write("                    tr.append(tdPrice);\n");
      out.write("                    $(\"#tdBook\").append(tr);\n");
      out.write("                    $(\"#bookContent\").val(\"\");\n");
      out.write("                    $(\"#btnSubmit\").removeAttr(\"disabled\");\n");
      out.write("                });\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\r\n");
      out.write("            //全选功能\r\n");
      out.write("            $(\"#ckAll\").click(function () {\r\n");
      out.write("                $(\".ck\").prop(\"checked\", $(this).prop(\"checked\"));\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //完成借阅功能\n");
      out.write("            $(\"#btnSubmit\").click(function () {\n");
      out.write("                if (!member) {\n");
      out.write("                    alert(\"请先查询会员信息\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                //1.获取用户选择的书籍编号(多本 1,2,3  1_2_3)\n");
      out.write("                var ids = [];\n");
      out.write("                var count = 0;\r\n");
      out.write("                $(\".ck\").each(function () {\r\n");
      out.write("                    if ($(this).prop(\"checked\")) {\r\n");
      out.write("                        ids.push($(this).val());\r\n");
      out.write("                        count++;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                if (count === 0) {\r\n");
      out.write("                    alert(\"请选择借阅书籍\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                if (count > member.type.amount) {\r\n");
      out.write("                    alert(\"借阅数量超出范围\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                //请求servlet http://localhost:8888/mybook_war_exploded/record?type=add&mid=1&ids=5_4_9_10\r\n");
      out.write("                location.href = \"record?type=add&mid=\" + member.id + \"&ids=\" + ids.join(\"_\") + \"&redirect=book_rent.jsp\";\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <!-- 头部开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"17\" valign=\"top\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/left_top_right.gif\" width=\"17\" height=\"29\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"top\" background=\"./Images/content_bg.gif\">\r\n");
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"16\" valign=\"top\" background=\"./Images/mail_right_bg.gif\"><img src=\"./Images/nav_right_bg.gif\"\r\n");
      out.write("                                                                                 width=\"16\" height=\"29\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 中间部分开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <!--第一行左边框-->\r\n");
      out.write("        <td valign=\"middle\" background=\"./Images/mail_left_bg.gif\">&nbsp;</td>\r\n");
      out.write("        <!--第一行中间内容-->\r\n");
      out.write("        <td valign=\"top\" bgcolor=\"#F7F8F9\">\r\n");
      out.write("            <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <!-- 空白行-->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td valign=\"top\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"4\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"100\" align=\"center\"><img src=\"./Images/mime.gif\"/></td>\r\n");
      out.write("                                <td valign=\"bottom\"><h3 style=\"letter-spacing:1px;\">常用功能 > 图书借阅 </h3></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 一条线 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"20\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 会员信息开始 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"96%\">\r\n");
      out.write("                        <fieldset>\r\n");
      out.write("                            <legend>查询会员</legend>\r\n");
      out.write("                            <table width=\"100%\" border=\"0\" class=\"cont\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td width=\"8%\" class=\"run-right\"> 会员编号</td>\r\n");
      out.write("                                    <td colspan=\"7\"><input class=\"text\" type=\"text\" id=\"memberId\" name=\"memberId\"/>\r\n");
      out.write("                                        <input type=\"button\" id=\"btnQuery\" value=\"确定\" style=\"width: 80px;\"/></td>\r\n");
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td width=\"8%\" class=\"run-right\">会员名称</td>\r\n");
      out.write("                                    <td width=\"17%\"><input class=\"text\" type=\"text\" id=\"name\" disabled/></td>\r\n");
      out.write("                                    <td width=\"8%\" class=\"run-right\">会员类型:</td>\r\n");
      out.write("                                    <td width=\"17%\"><input class=\"text\" type=\"text\" id=\"type\" disabled/></td>\r\n");
      out.write("                                    <td width=\"8%\" class=\"run-right\">账户余额</td>\r\n");
      out.write("                                    <td width=\"17%\"><input class=\"text\" type=\"text\" id=\"balance\" disabled/></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <!--空行-->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"3\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                <!--图书搜索条-->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"96%\">\r\n");
      out.write("                        <fieldset>\r\n");
      out.write("                            <legend>查询图书</legend>\r\n");
      out.write("                            <table width=\"100%\" border=\"1\" class=\"cont\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=\"8\">\r\n");
      out.write("\r\n");
      out.write("                                        请输入:&nbsp;&nbsp;<input class=\"text\" type=\"text\" id=\"bookContent\"\r\n");
      out.write("                                                               name=\"bookContent\" placeholder=\"输入条形码/书名\"/>\r\n");
      out.write("                                        <input type=\"button\" id=\"btnQueryBook\" value=\"确定\" style=\"width: 80px;\"/>\r\n");
      out.write("                                        <input type=\"button\" id=\"btnSubmit\" value=\"完成借阅\" style=\"width: 80px;\"/>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"20\" colspan=\"3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"96%\">\r\n");
      out.write("                        <table width=\"100%\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\">\r\n");
      out.write("                                    <form action=\"\" method=\"\">\r\n");
      out.write("                                        <table width=\"100%\" class=\"cont tr_color\" id=\"tdBook\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th><input type=\"checkbox\" id=\"ckAll\" checked/>全选/全不选</th>\r\n");
      out.write("                                                <th>书籍名</th>\r\n");
      out.write("                                                <th>借阅时间</th>\r\n");
      out.write("                                                <th>应还时间</th>\r\n");
      out.write("                                                <th>出版社</th>\r\n");
      out.write("                                                <th>书架</th>\r\n");
      out.write("                                                <th>定价(元)</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 产品列表结束 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"51%\" class=\"left_txt\">\r\n");
      out.write("                        <img src=\"./Images/icon_mail.gif\" width=\"16\" height=\"11\"> 客户服务邮箱：1109132@qq.com<br/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/mail_right_bg.gif\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 底部部分 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_left.gif\" width=\"17\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/buttom_bgs.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_bgs.gif\" width=\"17\" height=\"17\">\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_right_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_right.gif\" width=\"16\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
