/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2025-12-20 17:32:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"图书 java jsp\"/>\r\n");
      out.write("    <meta http-equiv=\"author\" content=\"phenix\"/>\r\n");
      out.write("    <script src=\"./Js/prototype.lite.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./Js/moo.fx.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./Js/moo.fx.pack.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./Style/skin.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        window.onload = function () {\r\n");
      out.write("            var contents = document.getElementsByClassName('content');\r\n");
      out.write("            var toggles = document.getElementsByClassName('type');\r\n");
      out.write("\r\n");
      out.write("            var myAccordion = new fx.Accordion(\r\n");
      out.write("                toggles, contents, {opacity: true, duration: 400}\r\n");
      out.write("            );\r\n");
      out.write("            myAccordion.showThisHideOpen(contents[0]);\r\n");
      out.write("            for (var i = 0; i < document.getElementsByTagName(\"a\").length; i++) {\r\n");
      out.write("                var dl_a = document.getElementsByTagName(\"a\")[i];\r\n");
      out.write("                dl_a.onfocus = function () {\r\n");
      out.write("                    this.blur();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" height=\"200\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"182\" valign=\"top\">\r\n");
      out.write("            <div id=\"container\">\r\n");
      out.write("                <h1 class=\"type\"><a href=\"javascript:void(0)\">会员管理</a></h1>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"./member?type=addpre\" target=\"main\">会员开卡</a></li>\r\n");
      out.write("                        <li><a href=\"./member?type=query\" target=\"main\">会员管理</a></li>\r\n");
      out.write("                        <li><a href=\"./mem_recharge.jsp\" target=\"main\">会员充值</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"type\"><a href=\"javascript:void(0)\">图书管理</a></h1>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"./book_add.jsp\" target=\"main\">添加图书</a></li>\r\n");
      out.write("                        <li><a href=\"./book?type=query&pageIndex=1\" target=\"main\">图书列表</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"type\"><a href=\"javascript:void(0)\">图书类型管理</a></h1>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"type_add.jsp\" target=\"main\">添加类型</a></li>\r\n");
      out.write("                        <li><a href=\"type_list.jsp\" target=\"main\">类型列表</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"type\"><a href=\"javascript:void(0)\">常用操作</a></h1>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"./book_rent.jsp\" target=\"main\">图书借阅</a></li>\r\n");
      out.write("                        <li><a href=\"./return_list.jsp\" target=\"main\">图书归还</a></li>\r\n");
      out.write("                        <li><a href=\"./rent_list.jsp\" target=\"main\">查看借阅历史信息</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- *********** -->\r\n");
      out.write("                <h1 class=\"type\"><a href=\"javascript:void(0)\">个人中心</a></h1>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"./set_pwd.jsp\" target=\"main\">修改密码</a></li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- *********** -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><img src=\"./Images/menu_top_line.gif\" width=\"182\" height=\"5\"/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <ul class=\"RM\">\r\n");
      out.write("                        <li><a href=\"javascript:void(0)\" target=\"main\">友情连接</a></li>\r\n");
      out.write("                        <li><a href=\"javascript:void(0)\" target=\"main\">在线留言</a></li>\r\n");
      out.write("                        <li><a href=\"javascript:void(0)\" target=\"main\">网站投票</a></li>\r\n");
      out.write("                        <li><a href=\"javascript:void(0)\" target=\"main\">邮箱设置</a></li>\r\n");
      out.write("                        <li><a href=\"javascript:void(0)\" target=\"main\">图片上传</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- *********** -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
