/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2025-12-18 14:19:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class set_005fpwd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"图书 java jsp\"/>\r\n");
      out.write("    <meta http-equiv=\"author\" content=\"phenix\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./Style/skin.css\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <!-- 头部开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"17\" valign=\"top\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/left_top_right.gif\" width=\"17\" height=\"29\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"top\" background=\"./Images/content_bg.gif\">\r\n");
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        <td width=\"16\" valign=\"top\" background=\"./Images/mail_right_bg.gif\"><img src=\"./Images/nav_right_bg.gif\"\r\n");
      out.write("                                                                                 width=\"16\" height=\"29\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 中间部分开始 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <!--第一行左边框-->\r\n");
      out.write("        <td valign=\"middle\" background=\"./Images/mail_left_bg.gif\">&nbsp;</td>\r\n");
      out.write("        <!--第一行中间内容-->\r\n");
      out.write("        <td valign=\"top\" bgcolor=\"#F7F8F9\">\r\n");
      out.write("            <table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <!-- 空白行-->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td valign=\"top\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"4\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td width=\"100\" align=\"center\"><img src=\"./Images/mime.gif\"/></td>\r\n");
      out.write("                                <td valign=\"bottom\"><h3 style=\"letter-spacing:1px;\">个人管理 > 修改密码</h3></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 一条线 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 添加产品开始 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"96%\">\r\n");
      out.write("                        <table width=\"100%\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\">\r\n");
      out.write("                                    <form action=\"user?type=modifyPwd\" method=\"post\">\r\n");
      out.write("                                        <table width=\"100%\" class=\"cont\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td width=\"80px\">原密码：</td>\r\n");
      out.write("                                                <td width=\"150px\"><input class=\"text\" type=\"password\" name=\"pwd\"\r\n");
      out.write("                                                                         value=\"\"/></td>\r\n");
      out.write("                                                <td class=\"err\">*原密码不匹配</td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td width=\"80px\"> 新密码：</td>\r\n");
      out.write("                                                <td width=\"150px\"><input class=\"text\" type=\"password\" name=\"newpwd\"\r\n");
      out.write("                                                                         value=\"\"/></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td width=\"80px\">确认密码：</td>\r\n");
      out.write("                                                <td width=\"150px\"><input class=\"text\" type=\"password\" name=\"newpwd2\"\r\n");
      out.write("                                                                         value=\"\"/></td>\r\n");
      out.write("                                                <td class=\"err\">两次密码不相同</td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                                                <td width=\"80px\"></td>\r\n");
      out.write("                                                <td width=\"150px\"><input class=\"btn\" type=\"submit\" value=\"提交\"/></td>\r\n");
      out.write("                                                <td></td>\r\n");
      out.write("                                                <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <!-- 添加产品结束 -->\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"40\" colspan=\"4\">\r\n");
      out.write("                        <table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"2%\">&nbsp;</td>\r\n");
      out.write("                    <td width=\"51%\" class=\"left_txt\">\r\n");
      out.write("                        <img src=\"./Images/icon_mail.gif\" width=\"16\" height=\"11\"> 客户服务邮箱：1109132@qq.com<br/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                    <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/mail_right_bg.gif\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <!-- 底部部分 -->\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_left_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_left.gif\" width=\"17\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td background=\"./Images/buttom_bgs.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_bgs.gif\" width=\"17\" height=\"17\">\r\n");
      out.write("        </td>\r\n");
      out.write("        <td valign=\"bottom\" background=\"./Images/mail_right_bg.gif\">\r\n");
      out.write("            <img src=\"./Images/buttom_right.gif\" width=\"16\" height=\"17\"/>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
